### ISSUE TITLE
Compatibility AngelChest & Slimefun

### ISSUE THREAD

**Issue by xMikux** [VictorTedesco/BetterDeathScreen#1]
Hi, this is a good plugin!

But it has some duplicate item and compatibility problems on these two plugins,

Slimefun - If the item have soulbound, then it can be duplicated (Soulbound is when the player death, the item won't be drop out) 

AngelChest - It won't correct summon chest, but I don't know why it happens, but here have these two plugin errors.

https://pastebin.com/yLirG10c

**Comment by xMikux** [comment]
Add version info
![image](https://user-images.githubusercontent.com/26039249/168466334-ec3c76a5-5b99-4f01-a892-4c9c5bcd6ef5.png)

**Comment by VictorTedesco** [comment]
I will work on a fix, already know what to do. Thanks!

**Comment by VictorTedesco** [comment]
Looks like i fixed the issue, please download the latest release of the plugin and test.

**Comment by xMikux** [comment]
After I tested it, now it all work, don't have duplicate problem.

Thank you!

**Comment by xMikux** [comment]
Okay, I notice another strange bug, after I add the plugins to my main server.
The main world have keepInventory true, but AngelChest still spawn the chest

**Comment by xMikux** [comment]
![image](https://user-images.githubusercontent.com/26039249/168491462-0cbd265e-03eb-4eee-a961-3f6e24e7e3b4.png)

**Comment by VictorTedesco** [comment]
I will try to fix that later, i already created a fake PlayerDeathEvent when the world of the player has keepInventory on, with a empty ArrayList for the items part of the event, but for some reason, the plugin AngelChest put the items on the chest. You can contact the dev of the plugin and ask for a fix. But i will try implementing a solution for this problem.

**Comment by xMikux** [comment]
I have contacted plugin dev on spigot discussion.
Waiting there reply

**Comment by mfnalex** [comment]
Hi, I'm the author of AngelChest. The easiest solution would be to cancel the AngelChestSpawnPrepareEvent: https://github.com/JEFF-Media-GbR/AngelChestAPI

**Comment by xMikux** [comment]
After I test it on the BDS 1.4, now it all work perfectly.
