### ISSUE TITLE
Block Commands

### ISSUE THREAD

**Issue by Angelio22G** [VictorTedesco/BetterDeathScreen#6]
Opa, seu plugin é realmente muito bom mas seria legal e EXTREMAMENTE útil e necessário o bloqueio de comandos no modo espectador quando morre e espera para renascer...

**Comment by VictorTedesco** [comment]
Esse pedido já foi implementado, porém ainda não lancei uma release com essa funcionalidade.

https://github.com/VictorTedesco/BetterDeathScreen/blob/master/src/main/java/me/tedesk/bds/events/bukkit/PlayerCommandListener.java
