### ISSUE TITLE
Bug dupe

### ISSUE THREAD

**Issue by Comquister** [VictorTedesco/BetterDeathScreen#9]
![image](https://user-images.githubusercontent.com/77806985/187010671-771f1543-37f0-4fdb-bfe4-eb66f5ec733a.png)
esta dropando os itens e o grave esta criando outros no sistema dele

**Comment by VictorTedesco** [comment]
Será resolvido na próxima atualização. Porém, me mande o nome do seu plugin de itens.

**Comment by Comquister** [comment]
> Será resolvido na próxima atualização. Porém, me mande o nome do seu plugin de grave.

[Graves](https://www.spigotmc.org/resources/graves.74208/)
